name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.yamllint'
      - '**/CHANGELOG.md'
      - '**/README.md'
      - 'README.md'
      - 'Makefile'

  workflow_dispatch:

jobs:
  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.get-changed.outputs.all_changed_files }}
      count: ${{ steps.get-changed.outputs.all_changed_files_count }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: get-changed
        uses: tj-actions/changed-files@v37
        with:
          files_ignore: |
            .github/**
            .gitignore
            .yamllint
            **/CHANGELOG.md
            **/README.md
            README.md
            Makefile
          dir_names: true
          dir_names_max_depth: 1
          json: true
          escape_json: false

      - name: Print info
        id: print-info
        run: |
          echo folders: "${{ steps.get-changed.outputs.all_changed_files }}"
          echo count: "${{ steps.get-changed.outputs.all_changed_files_count }}"

  build-matrix:
    needs:
      - get-matrix
    if: needs.get-matrix.outputs.count > 0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.get-matrix.outputs.folders) }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up QEMU
        id: setup-qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create additional environment variables
        id: create-env-vars
        run: |
          echo "REPOSITORY=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.folder }}" >> $GITHUB_ENV
          if grep -i --quiet 'VERSION=' ${{ matrix.folder }}/Dockerfile ; then
            echo "VERSION=$(grep "VERSION=" ${{ matrix.folder }}/Dockerfile | cut -d '=' -f 2)" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Print info
        id: print-info
        run: |
          echo repository: $REPOSITORY
          echo version: $VERSION

      - name: Build and publish container
        id: build-push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ${{ matrix.folder }}
          tags: |
            ${{ env.REPOSITORY }}:latest
            ${{ env.REPOSITORY }}:${{ env.VERSION }}
